Visitors=

SUM(

fact_growth_events[visitors]

)

-------------------------

Signups=

SUM(

fact_growth_events[signups]

)

-------------------------

Signup Rate=

DIVIDE(

[Signups],

[Visitors]

)